### ISSUE TITLE
[1.20.1] Breaking Time for Trees

### ISSUE THREAD

**Issue by Loregart** [DynamicTreesTeam/DynamicTrees-Quark#14]
When Dynamic Trees Quark is installed, all Dynamic Trees can't get "chopped" faster with an axe. 
The breaking time is very long for all Dynamic Trees Blocks. :( 

I tested it on 1.20.1 with the 2.5.0 version of the mod.

**Comment by supermassimo** [comment]
should be fixed on 2.5.1
